#!/usr/bin/env python3
"""
make_carousel_assets.py — resize real photos (not drawings) into responsive
WebP assets for the hero carousel.

Unlike digitize.py/process_art.py, this does NOT touch color/paper/alpha —
these are ordinary photos and should be kept as shot, just resized and
re-encoded. It:
  1. Auto-orients each photo via its EXIF tag
  2. Resizes it to a few widths for a srcset
  3. Encodes each to WebP
  4. Writes src/data/heroCarousel.ts describing every processed slide, so the
     Vue carousel component just renders whatever this script produced —
     re-run it after adding/removing photos and the site picks them up.

Usage:
    python3 tools/make_carousel_assets.py

Reads from:  tools/source-images/carrousel/carrusel*.jpg  (full-res originals,
             kept out of public/ so they never ship to production)
Writes to:   public/carrusel-<n>-<width>.webp
             src/data/heroCarousel.ts
"""
from __future__ import annotations

import re
from pathlib import Path

from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = ROOT / "tools" / "source-images" / "carrousel"
PUBLIC_DIR = ROOT / "public"
MANIFEST_PATH = ROOT / "src" / "data" / "heroCarousel.ts"
WIDTHS = [480, 900, 1400]
QUALITY = 82


def natural_key(p: Path) -> int:
    m = re.search(r"(\d+)", p.stem)
    return int(m.group(1)) if m else 0


def main() -> None:
    files = sorted(SRC_DIR.glob("carrusel*.jpg"), key=natural_key)
    if not files:
        raise SystemExit(f"No carrusel*.jpg files found in {SRC_DIR}")

    slides = []
    for f in files:
        n = natural_key(f)
        img = ImageOps.exif_transpose(Image.open(f))
        if img.mode != "RGB":
            img = img.convert("RGB")
        w0, h0 = img.size

        seen_widths: set[int] = set()
        srcset_parts: list[str] = []
        largest_name = ""
        largest_w = 0

        for w in WIDTHS:
            if w >= w0:
                out_img, out_w = img, w0
            else:
                out_h = round(h0 * (w / w0))
                out_img = img.resize((w, out_h), Image.LANCZOS)
                out_w = w

            if out_w in seen_widths:
                continue
            seen_widths.add(out_w)

            out_name = f"carrusel-{n}-{out_w}.webp"
            out_img.save(
                PUBLIC_DIR / out_name, "WEBP", quality=QUALITY, method=6
            )
            srcset_parts.append(f"/{out_name} {out_w}w")
            if out_w > largest_w:
                largest_w = out_w
                largest_name = out_name

        orientation = "portrait" if h0 > w0 else "landscape"
        slides.append(
            {
                "id": f"carrusel-{n}",
                "width": w0,
                "height": h0,
                "src": f"/{largest_name}",
                "srcset": ", ".join(srcset_parts),
            }
        )
        print(f"  {f.name} -> {len(srcset_parts)} sizes ({w0}x{h0}, {orientation})")

    lines = [
        "// AUTO-GENERATED by tools/make_carousel_assets.py — do not edit by hand.",
        "// Re-run the script after adding/removing photos in",
        "// tools/source-images/carrousel/ to regenerate this file.",
        "",
        "export interface CarouselSlide {",
        "  id: string",
        "  width: number",
        "  height: number",
        "  src: string",
        "  srcset: string",
        "}",
        "",
        "export const heroCarouselSlides: CarouselSlide[] = [",
    ]
    for s in slides:
        lines.append("  {")
        lines.append(f"    id: '{s['id']}',")
        lines.append(f"    width: {s['width']},")
        lines.append(f"    height: {s['height']},")
        lines.append(f"    src: '{s['src']}',")
        lines.append(f"    srcset: '{s['srcset']}',")
        lines.append("  },")
    lines.append("]")
    lines.append("")

    MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"\nWrote {MANIFEST_PATH.relative_to(ROOT)} with {len(slides)} slides.")


if __name__ == "__main__":
    main()
