// AUTO-GENERATED by tools/make_carousel_assets.py — do not edit by hand.
// Re-run the script after adding/removing photos in
// tools/source-images/carrousel/ to regenerate this file.

export interface CarouselSlide {
  id: string
  width: number
  height: number
  src: string
  srcset: string
}

export const heroCarouselSlides: CarouselSlide[] = [
  {
    id: 'carrusel-1',
    width: 6000,
    height: 4000,
    src: '/carrusel-1-1400.webp',
    srcset:
      '/carrusel-1-480.webp 480w, /carrusel-1-900.webp 900w, /carrusel-1-1400.webp 1400w',
  },
  {
    id: 'carrusel-2',
    width: 6000,
    height: 4000,
    src: '/carrusel-2-1400.webp',
    srcset:
      '/carrusel-2-480.webp 480w, /carrusel-2-900.webp 900w, /carrusel-2-1400.webp 1400w',
  },
  {
    id: 'carrusel-3',
    width: 3501,
    height: 5252,
    src: '/carrusel-3-1400.webp',
    srcset:
      '/carrusel-3-480.webp 480w, /carrusel-3-900.webp 900w, /carrusel-3-1400.webp 1400w',
  },
  {
    id: 'carrusel-4',
    width: 5262,
    height: 3508,
    src: '/carrusel-4-1400.webp',
    srcset:
      '/carrusel-4-480.webp 480w, /carrusel-4-900.webp 900w, /carrusel-4-1400.webp 1400w',
  },
  {
    id: 'carrusel-5',
    width: 3713,
    height: 5569,
    src: '/carrusel-5-1400.webp',
    srcset:
      '/carrusel-5-480.webp 480w, /carrusel-5-900.webp 900w, /carrusel-5-1400.webp 1400w',
  },
]
